import 'product.dart';

List<Product> productList = [
  Product(
    1,
    productId: '01',
    name: 'Luminara Lamp',
    imageUrl: 'assets/Luminara Lamp.png',
    category: 'Popular',
    price: 23000,
  ),
  Product(
    1,
    productId: '02',
    name: 'Zenith Desk',
    imageUrl: 'assets/Zenith Desk.png',
    category: 'Table',
    price: 40000,
  ),
  Product(
    1,
    productId: '03',
    name: 'Latte Lounger',
    imageUrl: 'assets/Latte Lounger.jpg',
    category: 'Chair',
    price: 80000,
  ),
  Product(
    1,
    productId: '04',
    name: 'Vertex Stand',
    imageUrl: 'assets/Vertex Stand.png',
    category: 'Table',
    price: 30000,
  ),
  Product(
    1,
    productId: '05',
    name: 'Athena Lamp',
    imageUrl: 'assets/Athena Lamp.jpg',
    category: 'Popular',
    price: 30000,
  ),
  Product(
    1,
    productId: '06',
    name: 'Freeda Lounge',
    imageUrl: 'assets/Freeda Lounge.jpg',
    category: 'Sofa',
    price: 90000,
  ),
  Product(
    1,
    productId: '07',
    name: 'Serendipity Desk',
    imageUrl: 'assets/serendipity desk.jpg',
    category: 'Table',
    price: 70000,
  ),
  Product(
    1,
    productId: '08',
    name: 'Nirvana Sofa',
    imageUrl: 'assets/Nirvana sofa.jpg',
    category: 'Sofa',
    price: 70000,
  ),
  Product(
    1,
    productId: '09',
    name: 'Platos Seat',
    imageUrl: 'assets/Platos Seat.png',
    category: 'Chair',
    price: 70000,
  ),
];
